"""add motocamping_details

Revision ID: 0bd5c499114a
Revises: 54e8eef4e2b7
Create Date: 2026-08-13 00:37:51.243656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd5c499114a'
down_revision: Union[str, None] = '54e8eef4e2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motocamping_details',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_name', sa.String(length=255), nullable=True),
    sa.Column('fuel_capacity_gal', sa.Float(), nullable=True),
    sa.Column('fuel_economy_mpg', sa.Float(), nullable=True),
    sa.Column('daily_ride_target_miles', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motocamping_details')
    # ### end Alembic commands ###
