"""fuel range fields, location address, collapse gear required level

Revision ID: 3726c250624c
Revises: 798fa42f0f0c
Create Date: 2026-08-16 02:01:30.961101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3726c250624c'
down_revision: Union[str, None] = '798fa42f0f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('trip_collaborators', sa.Column('fuel_range_miles', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('owner_fuel_range_miles', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # required_level dropped its 'suggested' tier — fold those rows into
    # 'optional' so existing data still deserializes against the new enum.
    op.execute("UPDATE gear SET required_level = 'optional' WHERE required_level = 'suggested'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'owner_fuel_range_miles')
    op.drop_column('trip_collaborators', 'fuel_range_miles')
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
