"""add trip collaborators and invites

Revision ID: 4bbb997442d6
Revises: ecc4de5df0f4
Create Date: 2026-08-13 23:20:02.189421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbb997442d6'
down_revision: Union[str, None] = 'ecc4de5df0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_collaborator')
    )
    op.create_index(op.f('ix_trip_collaborators_trip_id'), 'trip_collaborators', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_user_id'), 'trip_collaborators', ['user_id'], unique=False)
    op.create_table('trip_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_invites_token'), 'trip_invites', ['token'], unique=True)
    op.create_index(op.f('ix_trip_invites_trip_id'), 'trip_invites', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_invites_trip_id'), table_name='trip_invites')
    op.drop_index(op.f('ix_trip_invites_token'), table_name='trip_invites')
    op.drop_table('trip_invites')
    op.drop_index(op.f('ix_trip_collaborators_user_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_trip_id'), table_name='trip_collaborators')
    op.drop_table('trip_collaborators')
    # ### end Alembic commands ###
