"""add camping_details

Revision ID: 6922b7e50cba
Revises: a81da9cb162d
Create Date: 2026-08-14 00:28:46.089741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6922b7e50cba'
down_revision: Union[str, None] = 'a81da9cb162d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camping_details',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('campground_reservation_ref', sa.String(length=255), nullable=True),
    sa.Column('fire_restrictions_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camping_details')
    # ### end Alembic commands ###
