"""add activity todos

Revision ID: 798fa42f0f0c
Revises: ffd35bf4e03c
Create Date: 2026-08-16 01:11:01.834670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798fa42f0f0c'
down_revision: Union[str, None] = 'ffd35bf4e03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('todos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'todos')
    # ### end Alembic commands ###
