"""add location contact fields, vehicle roster, gear metadata, tasks, expense splitting

Revision ID: 8fde417ea382
Revises: 90e50de89c1e
Create Date: 2026-08-16 00:31:56.158097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fde417ea382'
down_revision: Union[str, None] = '90e50de89c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_trip_id'), 'tasks', ['trip_id'], unique=False)
    op.create_table('expense_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_participant')
    )
    op.create_index(op.f('ix_expense_participants_expense_id'), 'expense_participants', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_participants_user_id'), 'expense_participants', ['user_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_paid_by_user_id_users', 'users', ['paid_by_user_id'], ['id'])

    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'required_level',
                sa.Enum('required', 'suggested', 'optional', name='gearrequiredlevel', native_enum=False),
                nullable=False,
                server_default='required',
            )
        )
        batch_op.add_column(sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_gear_assigned_to_user_id_users', 'users', ['assigned_to_user_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confirmation_ref', sa.String(length=255), nullable=True))

    with op.batch_alter_table('trip_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle', sa.String(length=255), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_vehicle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('owner_vehicle')

    with op.batch_alter_table('trip_collaborators', schema=None) as batch_op:
        batch_op.drop_column('vehicle')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('confirmation_ref')
        batch_op.drop_column('contact_phone')

    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gear_assigned_to_user_id_users', type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('assigned_to_user_id')
        batch_op.drop_column('required_level')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_paid_by_user_id_users', type_='foreignkey')
        batch_op.drop_column('paid_by_user_id')

    op.drop_index(op.f('ix_expense_participants_user_id'), table_name='expense_participants')
    op.drop_index(op.f('ix_expense_participants_expense_id'), table_name='expense_participants')
    op.drop_table('expense_participants')
    op.drop_index(op.f('ix_tasks_trip_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
