"""add international_details

Revision ID: 90e50de89c1e
Revises: 6922b7e50cba
Create Date: 2026-08-14 00:50:38.532739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e50de89c1e'
down_revision: Union[str, None] = '6922b7e50cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_details',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('home_currency', sa.String(length=3), nullable=True),
    sa.Column('destination_currencies', sa.JSON(), nullable=True),
    sa.Column('primary_timezone', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('international_details')
    # ### end Alembic commands ###
