"""add overlanding_details

Revision ID: a81da9cb162d
Revises: 4bbb997442d6
Create Date: 2026-08-14 00:04:02.978568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81da9cb162d'
down_revision: Union[str, None] = '4bbb997442d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overlanding_details',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=255), nullable=True),
    sa.Column('fuel_capacity_gal', sa.Float(), nullable=True),
    sa.Column('fuel_economy_mpg', sa.Float(), nullable=True),
    sa.Column('ground_clearance_in', sa.Float(), nullable=True),
    sa.Column('drivetrain', sa.String(length=50), nullable=True),
    sa.Column('has_recovery_gear', sa.Boolean(), nullable=True),
    sa.Column('comms_plan', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overlanding_details')
    # ### end Alembic commands ###
