"""mode-specific planning fields for backpacking overlanding camping international

Revision ID: b8a4c26468e8
Revises: caaa604a175d
Create Date: 2026-08-16 12:04:16.864375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a4c26468e8'
down_revision: Union[str, None] = 'caaa604a175d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backpacking_details', sa.Column('bear_canister_required', sa.Boolean(), nullable=True))
    op.add_column('backpacking_details', sa.Column('water_capacity_liters', sa.Float(), nullable=True))
    op.add_column('backpacking_details', sa.Column('longest_dry_stretch_mi', sa.Float(), nullable=True))
    op.add_column('backpacking_details', sa.Column('total_distance_mi', sa.Float(), nullable=True))
    op.add_column('backpacking_details', sa.Column('elevation_gain_ft', sa.Float(), nullable=True))
    op.add_column('camping_details', sa.Column('potable_water_available', sa.Boolean(), nullable=True))
    op.add_column('camping_details', sa.Column('firewood_policy', sa.String(length=50), nullable=True))
    op.add_column('camping_details', sa.Column('check_in_time', sa.String(length=50), nullable=True))
    op.add_column('camping_details', sa.Column('quiet_hours', sa.String(length=50), nullable=True))
    op.add_column('camping_details', sa.Column('meal_plan', sa.Text(), nullable=True))
    op.add_column('international_details', sa.Column('passport_expiry', sa.Date(), nullable=True))
    op.add_column('international_details', sa.Column('visa_required', sa.Boolean(), nullable=True))
    op.add_column('international_details', sa.Column('visa_notes', sa.Text(), nullable=True))
    op.add_column('international_details', sa.Column('vaccinations_notes', sa.Text(), nullable=True))
    op.add_column('international_details', sa.Column('travel_insurance_ref', sa.String(length=255), nullable=True))
    op.add_column('international_details', sa.Column('embassy_contact', sa.String(length=255), nullable=True))
    op.add_column('international_details', sa.Column('step_enrolled', sa.Boolean(), nullable=True))
    op.add_column('overlanding_details', sa.Column('tire_pressure_offroad_psi', sa.Float(), nullable=True))
    op.add_column('overlanding_details', sa.Column('tire_pressure_highway_psi', sa.Float(), nullable=True))
    op.add_column('overlanding_details', sa.Column('water_capacity_gal', sa.Float(), nullable=True))
    op.add_column('overlanding_details', sa.Column('aux_fuel_gal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overlanding_details', 'aux_fuel_gal')
    op.drop_column('overlanding_details', 'water_capacity_gal')
    op.drop_column('overlanding_details', 'tire_pressure_highway_psi')
    op.drop_column('overlanding_details', 'tire_pressure_offroad_psi')
    op.drop_column('international_details', 'step_enrolled')
    op.drop_column('international_details', 'embassy_contact')
    op.drop_column('international_details', 'travel_insurance_ref')
    op.drop_column('international_details', 'vaccinations_notes')
    op.drop_column('international_details', 'visa_notes')
    op.drop_column('international_details', 'visa_required')
    op.drop_column('international_details', 'passport_expiry')
    op.drop_column('camping_details', 'meal_plan')
    op.drop_column('camping_details', 'quiet_hours')
    op.drop_column('camping_details', 'check_in_time')
    op.drop_column('camping_details', 'firewood_policy')
    op.drop_column('camping_details', 'potable_water_available')
    op.drop_column('backpacking_details', 'elevation_gain_ft')
    op.drop_column('backpacking_details', 'total_distance_mi')
    op.drop_column('backpacking_details', 'longest_dry_stretch_mi')
    op.drop_column('backpacking_details', 'water_capacity_liters')
    op.drop_column('backpacking_details', 'bear_canister_required')
    # ### end Alembic commands ###
