"""add trip invite invitee email

Revision ID: caaa604a175d
Revises: 3726c250624c
Create Date: 2026-08-16 11:19:13.451744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaa604a175d'
down_revision: Union[str, None] = '3726c250624c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_invites', sa.Column('invitee_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_trip_invites_invitee_email'), 'trip_invites', ['invitee_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_invites_invitee_email'), table_name='trip_invites')
    op.drop_column('trip_invites', 'invitee_email')
    # ### end Alembic commands ###
