"""add backpacking_details

Revision ID: ecc4de5df0f4
Revises: 0bd5c499114a
Create Date: 2026-08-13 01:05:46.355425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4de5df0f4'
down_revision: Union[str, None] = '0bd5c499114a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backpacking_details',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('base_pack_weight_oz', sa.Float(), nullable=True),
    sa.Column('permit_required', sa.Boolean(), nullable=True),
    sa.Column('permit_notes', sa.Text(), nullable=True),
    sa.Column('resupply_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backpacking_details')
    # ### end Alembic commands ###
